/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: counter.proto
// Protobuf Java Version: 4.29.3

package com.alipay.sofa.jraft.example.counter.rpc;

public final class CounterOutter {
    private CounterOutter() {
    }

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
            com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
            /* major= */4,
            /* minor= */29,
            /* patch= */3,
            /* suffix= */"", CounterOutter.class.getName());
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface GetValueRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jraft.GetValueRequest)
                                             com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required bool readOnlySafe = 1;</code>
         * @return Whether the readOnlySafe field is set.
         */
        boolean hasReadOnlySafe();

        /**
         * <code>required bool readOnlySafe = 1;</code>
         * @return The readOnlySafe.
         */
        boolean getReadOnlySafe();
    }

    /**
     * Protobuf type {@code jraft.GetValueRequest}
     */
    public static final class GetValueRequest extends com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:jraft.GetValueRequest)
                                                                                          GetValueRequestOrBuilder {
        private static final long serialVersionUID = 0L;
        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */4,
                /* minor= */29,
                /* patch= */3,
                /* suffix= */"", GetValueRequest.class.getName());
        }

        // Use GetValueRequest.newBuilder() to construct.
        private GetValueRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private GetValueRequest() {
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.internal_static_jraft_GetValueRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.internal_static_jraft_GetValueRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest.class,
                    com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest.Builder.class);
        }

        private int             bitField0_;
        public static final int READONLYSAFE_FIELD_NUMBER = 1;
        private boolean         readOnlySafe_             = false;

        /**
         * <code>required bool readOnlySafe = 1;</code>
         * @return Whether the readOnlySafe field is set.
         */
        @java.lang.Override
        public boolean hasReadOnlySafe() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>required bool readOnlySafe = 1;</code>
         * @return The readOnlySafe.
         */
        @java.lang.Override
        public boolean getReadOnlySafe() {
            return readOnlySafe_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            if (!hasReadOnlySafe()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeBool(1, readOnlySafe_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream.computeBoolSize(1, readOnlySafe_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest)) {
                return super.equals(obj);
            }
            com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest other = (com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest) obj;

            if (hasReadOnlySafe() != other.hasReadOnlySafe())
                return false;
            if (hasReadOnlySafe()) {
                if (getReadOnlySafe() != other.getReadOnlySafe())
                    return false;
            }
            if (!getUnknownFields().equals(other.getUnknownFields()))
                return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasReadOnlySafe()) {
                hash = (37 * hash) + READONLYSAFE_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getReadOnlySafe());
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest parseFrom(java.nio.ByteBuffer data)
                                                                                                                                 throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest parseFrom(java.nio.ByteBuffer data,
                                                                                                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                    throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest parseFrom(com.google.protobuf.ByteString data)
                                                                                                                                            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest parseFrom(com.google.protobuf.ByteString data,
                                                                                                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                    throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest parseFrom(byte[] data)
                                                                                                                    throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest parseFrom(byte[] data,
                                                                                                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                    throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest parseFrom(java.io.InputStream input)
                                                                                                                                  throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest parseFrom(java.io.InputStream input,
                                                                                                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                    throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest parseDelimitedFrom(java.io.InputStream input)
                                                                                                                                           throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest parseDelimitedFrom(java.io.InputStream input,
                                                                                                                 com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                             throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest parseFrom(com.google.protobuf.CodedInputStream input)
                                                                                                                                                   throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest parseFrom(com.google.protobuf.CodedInputStream input,
                                                                                                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                    throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code jraft.GetValueRequest}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
                                                                                                       implements
                                                                                                       // @@protoc_insertion_point(builder_implements:jraft.GetValueRequest)
                                                                                                       com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.internal_static_jraft_GetValueRequest_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.internal_static_jraft_GetValueRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                        com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest.class,
                        com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest.Builder.class);
            }

            // Construct using com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest.newBuilder()
            private Builder() {

            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                readOnlySafe_ = false;
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.internal_static_jraft_GetValueRequest_descriptor;
            }

            @java.lang.Override
            public com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest getDefaultInstanceForType() {
                return com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest.getDefaultInstance();
            }

            @java.lang.Override
            public com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest build() {
                com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest buildPartial() {
                com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest result = new com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest(
                    this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest result) {
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.readOnlySafe_ = readOnlySafe_;
                    to_bitField0_ |= 0x00000001;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest) {
                    return mergeFrom((com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest other) {
                if (other == com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest
                    .getDefaultInstance())
                    return this;
                if (other.hasReadOnlySafe()) {
                    setReadOnlySafe(other.getReadOnlySafe());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasReadOnlySafe()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                                     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                 throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                readOnlySafe_ = input.readBool();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 8
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int     bitField0_;

            private boolean readOnlySafe_;

            /**
             * <code>required bool readOnlySafe = 1;</code>
             * @return Whether the readOnlySafe field is set.
             */
            @java.lang.Override
            public boolean hasReadOnlySafe() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>required bool readOnlySafe = 1;</code>
             * @return The readOnlySafe.
             */
            @java.lang.Override
            public boolean getReadOnlySafe() {
                return readOnlySafe_;
            }

            /**
             * <code>required bool readOnlySafe = 1;</code>
             * @param value The readOnlySafe to set.
             * @return This builder for chaining.
             */
            public Builder setReadOnlySafe(boolean value) {

                readOnlySafe_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>required bool readOnlySafe = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearReadOnlySafe() {
                bitField0_ = (bitField0_ & ~0x00000001);
                readOnlySafe_ = false;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:jraft.GetValueRequest)
        }

        // @@protoc_insertion_point(class_scope:jraft.GetValueRequest)
        private static final com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest();
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<GetValueRequest> PARSER = new com.google.protobuf.AbstractParser<GetValueRequest>() {
                                                                                    @java.lang.Override
                                                                                    public GetValueRequest parsePartialFrom(com.google.protobuf.CodedInputStream input,
                                                                                                                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                                        throws com.google.protobuf.InvalidProtocolBufferException {
                                                                                        Builder builder = newBuilder();
                                                                                        try {
                                                                                            builder.mergeFrom(input,
                                                                                                extensionRegistry);
                                                                                        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                                                                                            throw e
                                                                                                .setUnfinishedMessage(builder
                                                                                                    .buildPartial());
                                                                                        } catch (com.google.protobuf.UninitializedMessageException e) {
                                                                                            throw e
                                                                                                .asInvalidProtocolBufferException()
                                                                                                .setUnfinishedMessage(
                                                                                                    builder
                                                                                                        .buildPartial());
                                                                                        } catch (java.io.IOException e) {
                                                                                            throw new com.google.protobuf.InvalidProtocolBufferException(
                                                                                                e)
                                                                                                .setUnfinishedMessage(builder
                                                                                                    .buildPartial());
                                                                                        }
                                                                                        return builder.buildPartial();
                                                                                    }
                                                                                };

        public static com.google.protobuf.Parser<GetValueRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<GetValueRequest> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.GetValueRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface IncrementAndGetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jraft.IncrementAndGetRequest)
                                                    com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required int64 delta = 1;</code>
         * @return Whether the delta field is set.
         */
        boolean hasDelta();

        /**
         * <code>required int64 delta = 1;</code>
         * @return The delta.
         */
        long getDelta();
    }

    /**
     * Protobuf type {@code jraft.IncrementAndGetRequest}
     */
    public static final class IncrementAndGetRequest extends com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:jraft.IncrementAndGetRequest)
                                                                                                 IncrementAndGetRequestOrBuilder {
        private static final long serialVersionUID = 0L;
        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */4,
                /* minor= */29,
                /* patch= */3,
                /* suffix= */"", IncrementAndGetRequest.class.getName());
        }

        // Use IncrementAndGetRequest.newBuilder() to construct.
        private IncrementAndGetRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private IncrementAndGetRequest() {
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.internal_static_jraft_IncrementAndGetRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.internal_static_jraft_IncrementAndGetRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest.class,
                    com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest.Builder.class);
        }

        private int             bitField0_;
        public static final int DELTA_FIELD_NUMBER = 1;
        private long            delta_             = 0L;

        /**
         * <code>required int64 delta = 1;</code>
         * @return Whether the delta field is set.
         */
        @java.lang.Override
        public boolean hasDelta() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>required int64 delta = 1;</code>
         * @return The delta.
         */
        @java.lang.Override
        public long getDelta() {
            return delta_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            if (!hasDelta()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeInt64(1, delta_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream.computeInt64Size(1, delta_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest)) {
                return super.equals(obj);
            }
            com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest other = (com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest) obj;

            if (hasDelta() != other.hasDelta())
                return false;
            if (hasDelta()) {
                if (getDelta() != other.getDelta())
                    return false;
            }
            if (!getUnknownFields().equals(other.getUnknownFields()))
                return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasDelta()) {
                hash = (37 * hash) + DELTA_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getDelta());
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest parseFrom(java.nio.ByteBuffer data)
                                                                                                                                        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest parseFrom(java.nio.ByteBuffer data,
                                                                                                               com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                           throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest parseFrom(com.google.protobuf.ByteString data)
                                                                                                                                                   throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest parseFrom(com.google.protobuf.ByteString data,
                                                                                                               com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                           throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest parseFrom(byte[] data)
                                                                                                                           throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest parseFrom(byte[] data,
                                                                                                               com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                           throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest parseFrom(java.io.InputStream input)
                                                                                                                                         throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest parseFrom(java.io.InputStream input,
                                                                                                               com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                           throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest parseDelimitedFrom(java.io.InputStream input)
                                                                                                                                                  throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest parseDelimitedFrom(java.io.InputStream input,
                                                                                                                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                                    throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest parseFrom(com.google.protobuf.CodedInputStream input)
                                                                                                                                                          throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest parseFrom(com.google.protobuf.CodedInputStream input,
                                                                                                               com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                           throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code jraft.IncrementAndGetRequest}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
                                                                                                       implements
                                                                                                       // @@protoc_insertion_point(builder_implements:jraft.IncrementAndGetRequest)
                                                                                                       com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.internal_static_jraft_IncrementAndGetRequest_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.internal_static_jraft_IncrementAndGetRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                        com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest.class,
                        com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest.Builder.class);
            }

            // Construct using com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest.newBuilder()
            private Builder() {

            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                delta_ = 0L;
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.internal_static_jraft_IncrementAndGetRequest_descriptor;
            }

            @java.lang.Override
            public com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest getDefaultInstanceForType() {
                return com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest
                    .getDefaultInstance();
            }

            @java.lang.Override
            public com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest build() {
                com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest buildPartial() {
                com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest result = new com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest(
                    this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest result) {
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.delta_ = delta_;
                    to_bitField0_ |= 0x00000001;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest) {
                    return mergeFrom((com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest other) {
                if (other == com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest
                    .getDefaultInstance())
                    return this;
                if (other.hasDelta()) {
                    setDelta(other.getDelta());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasDelta()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                                     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                 throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                delta_ = input.readInt64();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 8
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int  bitField0_;

            private long delta_;

            /**
             * <code>required int64 delta = 1;</code>
             * @return Whether the delta field is set.
             */
            @java.lang.Override
            public boolean hasDelta() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>required int64 delta = 1;</code>
             * @return The delta.
             */
            @java.lang.Override
            public long getDelta() {
                return delta_;
            }

            /**
             * <code>required int64 delta = 1;</code>
             * @param value The delta to set.
             * @return This builder for chaining.
             */
            public Builder setDelta(long value) {

                delta_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 delta = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearDelta() {
                bitField0_ = (bitField0_ & ~0x00000001);
                delta_ = 0L;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:jraft.IncrementAndGetRequest)
        }

        // @@protoc_insertion_point(class_scope:jraft.IncrementAndGetRequest)
        private static final com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest();
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<IncrementAndGetRequest> PARSER = new com.google.protobuf.AbstractParser<IncrementAndGetRequest>() {
                                                                                           @java.lang.Override
                                                                                           public IncrementAndGetRequest parsePartialFrom(com.google.protobuf.CodedInputStream input,
                                                                                                                                          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                                                      throws com.google.protobuf.InvalidProtocolBufferException {
                                                                                               Builder builder = newBuilder();
                                                                                               try {
                                                                                                   builder
                                                                                                       .mergeFrom(
                                                                                                           input,
                                                                                                           extensionRegistry);
                                                                                               } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                                                                                                   throw e
                                                                                                       .setUnfinishedMessage(builder
                                                                                                           .buildPartial());
                                                                                               } catch (com.google.protobuf.UninitializedMessageException e) {
                                                                                                   throw e
                                                                                                       .asInvalidProtocolBufferException()
                                                                                                       .setUnfinishedMessage(
                                                                                                           builder
                                                                                                               .buildPartial());
                                                                                               } catch (java.io.IOException e) {
                                                                                                   throw new com.google.protobuf.InvalidProtocolBufferException(
                                                                                                       e)
                                                                                                       .setUnfinishedMessage(builder
                                                                                                           .buildPartial());
                                                                                               }
                                                                                               return builder
                                                                                                   .buildPartial();
                                                                                           }
                                                                                       };

        public static com.google.protobuf.Parser<IncrementAndGetRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<IncrementAndGetRequest> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.IncrementAndGetRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface ValueResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jraft.ValueResponse)
                                           com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required int64 value = 1;</code>
         * @return Whether the value field is set.
         */
        boolean hasValue();

        /**
         * <code>required int64 value = 1;</code>
         * @return The value.
         */
        long getValue();

        /**
         * <code>required bool success = 2;</code>
         * @return Whether the success field is set.
         */
        boolean hasSuccess();

        /**
         * <code>required bool success = 2;</code>
         * @return The success.
         */
        boolean getSuccess();

        /**
         * <code>optional string redirect = 3;</code>
         * @return Whether the redirect field is set.
         */
        boolean hasRedirect();

        /**
         * <code>optional string redirect = 3;</code>
         * @return The redirect.
         */
        java.lang.String getRedirect();

        /**
         * <code>optional string redirect = 3;</code>
         * @return The bytes for redirect.
         */
        com.google.protobuf.ByteString getRedirectBytes();

        /**
         * <code>optional string errorMsg = 4;</code>
         * @return Whether the errorMsg field is set.
         */
        boolean hasErrorMsg();

        /**
         * <code>optional string errorMsg = 4;</code>
         * @return The errorMsg.
         */
        java.lang.String getErrorMsg();

        /**
         * <code>optional string errorMsg = 4;</code>
         * @return The bytes for errorMsg.
         */
        com.google.protobuf.ByteString getErrorMsgBytes();
    }

    /**
     * Protobuf type {@code jraft.ValueResponse}
     */
    public static final class ValueResponse extends com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:jraft.ValueResponse)
                                                                                        ValueResponseOrBuilder {
        private static final long serialVersionUID = 0L;
        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */4,
                /* minor= */29,
                /* patch= */3,
                /* suffix= */"", ValueResponse.class.getName());
        }

        // Use ValueResponse.newBuilder() to construct.
        private ValueResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private ValueResponse() {
            redirect_ = "";
            errorMsg_ = "";
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.internal_static_jraft_ValueResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.internal_static_jraft_ValueResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse.class,
                    com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse.Builder.class);
        }

        private int             bitField0_;
        public static final int VALUE_FIELD_NUMBER = 1;
        private long            value_             = 0L;

        /**
         * <code>required int64 value = 1;</code>
         * @return Whether the value field is set.
         */
        @java.lang.Override
        public boolean hasValue() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>required int64 value = 1;</code>
         * @return The value.
         */
        @java.lang.Override
        public long getValue() {
            return value_;
        }

        public static final int SUCCESS_FIELD_NUMBER = 2;
        private boolean         success_             = false;

        /**
         * <code>required bool success = 2;</code>
         * @return Whether the success field is set.
         */
        @java.lang.Override
        public boolean hasSuccess() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>required bool success = 2;</code>
         * @return The success.
         */
        @java.lang.Override
        public boolean getSuccess() {
            return success_;
        }

        public static final int           REDIRECT_FIELD_NUMBER = 3;
        @SuppressWarnings("serial")
        private volatile java.lang.Object redirect_             = "";

        /**
         * <code>optional string redirect = 3;</code>
         * @return Whether the redirect field is set.
         */
        @java.lang.Override
        public boolean hasRedirect() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        /**
         * <code>optional string redirect = 3;</code>
         * @return The redirect.
         */
        @java.lang.Override
        public java.lang.String getRedirect() {
            java.lang.Object ref = redirect_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    redirect_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string redirect = 3;</code>
         * @return The bytes for redirect.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getRedirectBytes() {
            java.lang.Object ref = redirect_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                redirect_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int           ERRORMSG_FIELD_NUMBER = 4;
        @SuppressWarnings("serial")
        private volatile java.lang.Object errorMsg_             = "";

        /**
         * <code>optional string errorMsg = 4;</code>
         * @return Whether the errorMsg field is set.
         */
        @java.lang.Override
        public boolean hasErrorMsg() {
            return ((bitField0_ & 0x00000008) != 0);
        }

        /**
         * <code>optional string errorMsg = 4;</code>
         * @return The errorMsg.
         */
        @java.lang.Override
        public java.lang.String getErrorMsg() {
            java.lang.Object ref = errorMsg_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    errorMsg_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string errorMsg = 4;</code>
         * @return The bytes for errorMsg.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getErrorMsgBytes() {
            java.lang.Object ref = errorMsg_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                errorMsg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            if (!hasValue()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasSuccess()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeInt64(1, value_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                output.writeBool(2, success_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 3, redirect_);
            }
            if (((bitField0_ & 0x00000008) != 0)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 4, errorMsg_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream.computeInt64Size(1, value_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.CodedOutputStream.computeBoolSize(2, success_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(3, redirect_);
            }
            if (((bitField0_ & 0x00000008) != 0)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(4, errorMsg_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse)) {
                return super.equals(obj);
            }
            com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse other = (com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse) obj;

            if (hasValue() != other.hasValue())
                return false;
            if (hasValue()) {
                if (getValue() != other.getValue())
                    return false;
            }
            if (hasSuccess() != other.hasSuccess())
                return false;
            if (hasSuccess()) {
                if (getSuccess() != other.getSuccess())
                    return false;
            }
            if (hasRedirect() != other.hasRedirect())
                return false;
            if (hasRedirect()) {
                if (!getRedirect().equals(other.getRedirect()))
                    return false;
            }
            if (hasErrorMsg() != other.hasErrorMsg())
                return false;
            if (hasErrorMsg()) {
                if (!getErrorMsg().equals(other.getErrorMsg()))
                    return false;
            }
            if (!getUnknownFields().equals(other.getUnknownFields()))
                return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasValue()) {
                hash = (37 * hash) + VALUE_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getValue());
            }
            if (hasSuccess()) {
                hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getSuccess());
            }
            if (hasRedirect()) {
                hash = (37 * hash) + REDIRECT_FIELD_NUMBER;
                hash = (53 * hash) + getRedirect().hashCode();
            }
            if (hasErrorMsg()) {
                hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
                hash = (53 * hash) + getErrorMsg().hashCode();
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse parseFrom(java.nio.ByteBuffer data)
                                                                                                                               throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse parseFrom(java.nio.ByteBuffer data,
                                                                                                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                  throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse parseFrom(com.google.protobuf.ByteString data)
                                                                                                                                          throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse parseFrom(com.google.protobuf.ByteString data,
                                                                                                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                  throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse parseFrom(byte[] data)
                                                                                                                  throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse parseFrom(byte[] data,
                                                                                                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                  throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse parseFrom(java.io.InputStream input)
                                                                                                                                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse parseFrom(java.io.InputStream input,
                                                                                                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                  throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse parseDelimitedFrom(java.io.InputStream input)
                                                                                                                                         throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse parseDelimitedFrom(java.io.InputStream input,
                                                                                                               com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                           throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse parseFrom(com.google.protobuf.CodedInputStream input)
                                                                                                                                                 throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse parseFrom(com.google.protobuf.CodedInputStream input,
                                                                                                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                  throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code jraft.ValueResponse}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
                                                                                                       implements
                                                                                                       // @@protoc_insertion_point(builder_implements:jraft.ValueResponse)
                                                                                                       com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.internal_static_jraft_ValueResponse_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.internal_static_jraft_ValueResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                        com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse.class,
                        com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse.Builder.class);
            }

            // Construct using com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse.newBuilder()
            private Builder() {

            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                value_ = 0L;
                success_ = false;
                redirect_ = "";
                errorMsg_ = "";
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.internal_static_jraft_ValueResponse_descriptor;
            }

            @java.lang.Override
            public com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse getDefaultInstanceForType() {
                return com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse.getDefaultInstance();
            }

            @java.lang.Override
            public com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse build() {
                com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse buildPartial() {
                com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse result = new com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse(
                    this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse result) {
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.value_ = value_;
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.success_ = success_;
                    to_bitField0_ |= 0x00000002;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.redirect_ = redirect_;
                    to_bitField0_ |= 0x00000004;
                }
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    result.errorMsg_ = errorMsg_;
                    to_bitField0_ |= 0x00000008;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse) {
                    return mergeFrom((com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse other) {
                if (other == com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse.getDefaultInstance())
                    return this;
                if (other.hasValue()) {
                    setValue(other.getValue());
                }
                if (other.hasSuccess()) {
                    setSuccess(other.getSuccess());
                }
                if (other.hasRedirect()) {
                    redirect_ = other.redirect_;
                    bitField0_ |= 0x00000004;
                    onChanged();
                }
                if (other.hasErrorMsg()) {
                    errorMsg_ = other.errorMsg_;
                    bitField0_ |= 0x00000008;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasValue()) {
                    return false;
                }
                if (!hasSuccess()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                                     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                 throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                value_ = input.readInt64();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 8
                            case 16: {
                                success_ = input.readBool();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 16
                            case 26: {
                                redirect_ = input.readBytes();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 26
                            case 34: {
                                errorMsg_ = input.readBytes();
                                bitField0_ |= 0x00000008;
                                break;
                            } // case 34
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int  bitField0_;

            private long value_;

            /**
             * <code>required int64 value = 1;</code>
             * @return Whether the value field is set.
             */
            @java.lang.Override
            public boolean hasValue() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>required int64 value = 1;</code>
             * @return The value.
             */
            @java.lang.Override
            public long getValue() {
                return value_;
            }

            /**
             * <code>required int64 value = 1;</code>
             * @param value The value to set.
             * @return This builder for chaining.
             */
            public Builder setValue(long value) {

                value_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 value = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearValue() {
                bitField0_ = (bitField0_ & ~0x00000001);
                value_ = 0L;
                onChanged();
                return this;
            }

            private boolean success_;

            /**
             * <code>required bool success = 2;</code>
             * @return Whether the success field is set.
             */
            @java.lang.Override
            public boolean hasSuccess() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <code>required bool success = 2;</code>
             * @return The success.
             */
            @java.lang.Override
            public boolean getSuccess() {
                return success_;
            }

            /**
             * <code>required bool success = 2;</code>
             * @param value The success to set.
             * @return This builder for chaining.
             */
            public Builder setSuccess(boolean value) {

                success_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>required bool success = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearSuccess() {
                bitField0_ = (bitField0_ & ~0x00000002);
                success_ = false;
                onChanged();
                return this;
            }

            private java.lang.Object redirect_ = "";

            /**
             * <code>optional string redirect = 3;</code>
             * @return Whether the redirect field is set.
             */
            public boolean hasRedirect() {
                return ((bitField0_ & 0x00000004) != 0);
            }

            /**
             * <code>optional string redirect = 3;</code>
             * @return The redirect.
             */
            public java.lang.String getRedirect() {
                java.lang.Object ref = redirect_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        redirect_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string redirect = 3;</code>
             * @return The bytes for redirect.
             */
            public com.google.protobuf.ByteString getRedirectBytes() {
                java.lang.Object ref = redirect_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                        .copyFromUtf8((java.lang.String) ref);
                    redirect_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string redirect = 3;</code>
             * @param value The redirect to set.
             * @return This builder for chaining.
             */
            public Builder setRedirect(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                redirect_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <code>optional string redirect = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearRedirect() {
                redirect_ = getDefaultInstance().getRedirect();
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }

            /**
             * <code>optional string redirect = 3;</code>
             * @param value The bytes for redirect to set.
             * @return This builder for chaining.
             */
            public Builder setRedirectBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                redirect_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            private java.lang.Object errorMsg_ = "";

            /**
             * <code>optional string errorMsg = 4;</code>
             * @return Whether the errorMsg field is set.
             */
            public boolean hasErrorMsg() {
                return ((bitField0_ & 0x00000008) != 0);
            }

            /**
             * <code>optional string errorMsg = 4;</code>
             * @return The errorMsg.
             */
            public java.lang.String getErrorMsg() {
                java.lang.Object ref = errorMsg_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        errorMsg_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string errorMsg = 4;</code>
             * @return The bytes for errorMsg.
             */
            public com.google.protobuf.ByteString getErrorMsgBytes() {
                java.lang.Object ref = errorMsg_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                        .copyFromUtf8((java.lang.String) ref);
                    errorMsg_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string errorMsg = 4;</code>
             * @param value The errorMsg to set.
             * @return This builder for chaining.
             */
            public Builder setErrorMsg(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                errorMsg_ = value;
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <code>optional string errorMsg = 4;</code>
             * @return This builder for chaining.
             */
            public Builder clearErrorMsg() {
                errorMsg_ = getDefaultInstance().getErrorMsg();
                bitField0_ = (bitField0_ & ~0x00000008);
                onChanged();
                return this;
            }

            /**
             * <code>optional string errorMsg = 4;</code>
             * @param value The bytes for errorMsg to set.
             * @return This builder for chaining.
             */
            public Builder setErrorMsgBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                errorMsg_ = value;
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:jraft.ValueResponse)
        }

        // @@protoc_insertion_point(class_scope:jraft.ValueResponse)
        private static final com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse();
        }

        public static com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<ValueResponse> PARSER = new com.google.protobuf.AbstractParser<ValueResponse>() {
                                                                                  @java.lang.Override
                                                                                  public ValueResponse parsePartialFrom(com.google.protobuf.CodedInputStream input,
                                                                                                                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                                    throws com.google.protobuf.InvalidProtocolBufferException {
                                                                                      Builder builder = newBuilder();
                                                                                      try {
                                                                                          builder.mergeFrom(input,
                                                                                              extensionRegistry);
                                                                                      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                                                                                          throw e
                                                                                              .setUnfinishedMessage(builder
                                                                                                  .buildPartial());
                                                                                      } catch (com.google.protobuf.UninitializedMessageException e) {
                                                                                          throw e
                                                                                              .asInvalidProtocolBufferException()
                                                                                              .setUnfinishedMessage(
                                                                                                  builder
                                                                                                      .buildPartial());
                                                                                      } catch (java.io.IOException e) {
                                                                                          throw new com.google.protobuf.InvalidProtocolBufferException(
                                                                                              e)
                                                                                              .setUnfinishedMessage(builder
                                                                                                  .buildPartial());
                                                                                      }
                                                                                      return builder.buildPartial();
                                                                                  }
                                                                              };

        public static com.google.protobuf.Parser<ValueResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ValueResponse> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.alipay.sofa.jraft.example.counter.rpc.CounterOutter.ValueResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor              internal_static_jraft_GetValueRequest_descriptor;
    private static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_jraft_GetValueRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor              internal_static_jraft_IncrementAndGetRequest_descriptor;
    private static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_jraft_IncrementAndGetRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor              internal_static_jraft_ValueResponse_descriptor;
    private static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_jraft_ValueResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = { "\n\rcounter.proto\022\005jraft\"\'\n\017GetValueReques"
                                              + "t\022\024\n\014readOnlySafe\030\001 \002(\010\"\'\n\026IncrementAndG"
                                              + "etRequest\022\r\n\005delta\030\001 \002(\003\"S\n\rValueRespons"
                                              + "e\022\r\n\005value\030\001 \002(\003\022\017\n\007success\030\002 \002(\010\022\020\n\010red"
                                              + "irect\030\003 \001(\t\022\020\n\010errorMsg\030\004 \001(\tB:\n)com.ali"
                                              + "pay.sofa.jraft.example.counter.rpcB\rCoun" + "terOutter" };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {});
        internal_static_jraft_GetValueRequest_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_jraft_GetValueRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_jraft_GetValueRequest_descriptor, new java.lang.String[] { "ReadOnlySafe", });
        internal_static_jraft_IncrementAndGetRequest_descriptor = getDescriptor().getMessageTypes().get(1);
        internal_static_jraft_IncrementAndGetRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_jraft_IncrementAndGetRequest_descriptor, new java.lang.String[] { "Delta", });
        internal_static_jraft_ValueResponse_descriptor = getDescriptor().getMessageTypes().get(2);
        internal_static_jraft_ValueResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_jraft_ValueResponse_descriptor, new java.lang.String[] { "Value", "Success", "Redirect",
            "ErrorMsg", });
        descriptor.resolveAllFeaturesImmutable();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
